# 2주차 : NumPy

1. OT 및 개발환경 세팅 (2주차 9/6)
2. <font color='red'>NumPy 입문 (3주차 9/13)</font> 
3. pandas 입문: 데이터 분석을 위한 넘파이의 변신 (4주차 9/20)
4. pandas 응용 : 같이 해보는 EDA (5주차 9/27)
5. sklearn을 통한 머신러닝 찍먹 (6주차 10/4)<br>
---------------------------- 7~9주차 중간고사 ----------------------------
6. opencv 입문 : 영상처리의 치트키 opencv (10주차 11/1)
7. opencv 응용 : 얼굴인식 + α? (11주차 11/8)
8. librosa를 활용한 audio denoising (12주차 11/15)  
---------------------------- 15주차 기말고사 ----------------------------  

## NumPy란?
>NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. ...  (Wikipedia)

- ### 사용법

In [4]:
import numpy as np

아나콘다에 기본적으로 설치되어있다! (없으면 pip install numpy or conda install numpy)

- ### Array (or ndarray) 생성

In [11]:
data = [1,2,3,4,5]
print(data)
print(type(data))

[1, 2, 3, 4, 5]
<class 'list'>


In [12]:
arr = np.array(data) # list to array
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [17]:
# 바로 만들기
arr = np.array([1,2,3,4,5]) # list to array
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [140]:
arr = np.array(1,2,3,4,5) # error

ValueError: only 2 non-keyword arguments accepted

In [143]:
# 다차원 array
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print()

arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


aragne

In [30]:
# np.aragne
arr = np.arange(15)
print(arr)

arr = np.arange(2,10,2)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[2 4 6 8]


ones/zeros

In [149]:
print(np.zeros((4,3))) 
print()

print(np.ones((4,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


eyes

In [155]:
print(np.eye(4,3)) # identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


- ### dtype과 shape

dtyp : array안 element의 datatype
+ 부호가 있는 정수 int(8, 16, 32, 64)
+ 부호가 없는 정수 uint(8 ,16, 32, 54)
+ 실수 float(16, 32, 64, 128)
+ 복소수 complex(64, 128, 256)
+ 불리언 bool
+ 문자열 string
+ 파이썬 오프젝트 object
+ 유니코드 unicode

In [46]:
np.array(['a','b']) 

array(['a', 'b'], dtype='<U1')

In [43]:
# dtype 확인
arr = np.array([1,2,3,4,5]) 
print(arr)
print(arr.dtype)
print()

arr = np.array([1.5, 2.7 ,3.1 ,4.2 ,5.0]) 
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32

[1.5 2.7 3.1 4.2 5. ]
float64


In [54]:
# dtype 변경
arr = np.array([1,2,3,4,5]) 
arr = arr.astype(np.float32) #arr.astype("float32")
print(arr.dtype)
print(arr)
print()

arr = np.array([1.5, 2.7 ,3.1 ,4.2 ,5.0]) 
arr = arr.astype(np.int64) # 주의! 버림이 된다 >> 필요시 따로 반올림 처리
print(arr.dtype)
print(arr)

float32
[1. 2. 3. 4. 5.]

int64
[1 2 3 4 5]


In [102]:
# 만들때 dtype 지정
arr = np.array([1,2,3,4,5],dtype=np.float32) 
print(arr.dtype)
print(arr)
print()

arr = np.array([1.5, 2.7 ,3.1 ,4.2 ,5.0],dtype=np.int64) 
print(arr.dtype)
print(arr)

float32
[1. 2. 3. 4. 5.]

int64
[1 2 3 4 5]


shape : 배열의 각 축(axis)의 크기 (ex. mxn matrix)

In [73]:
arr = np.array([1,2])
print(arr.shape)
print()

arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
print()

arr = np.array([[[1,2,3],[5,6,7],[9,10,11]]])
print(arr.shape)

(2,)

(2, 4)

(1, 3, 3)


cf. dimension : 차원, 축(axis)의 개수

In [79]:
arr = np.array([1,2])
print(arr.shape)
print(arr.ndim)
print()

arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
print(arr.ndim)
print()

arr = np.array([[[1,2,3],[5,6,7],[9,10,11]]])
print(arr.shape)
print(arr.ndim)

(2,)
1

(2, 4)
2

(1, 3, 3)
3


transpose

In [94]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.shape)
print()

arr = arr.T #transpose
print(arr)
print(arr.shape)
print()

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
(4, 2)



In [130]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.transpose(arr1)
arr3 = np.swapaxes(arr1,0,1)

print(arr2)
print(arr2.shape)
print()

print(arr3)
print(arr3.shape)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
(4, 2)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
(4, 2)


In [122]:
# 3차원
arr1 = np.array([[[1,2,3],[5,6,7]]])
print(arr1.shape)
print()

arr2 = arr.T
print(arr2)
print(arr2.shape)
print()

arr3 = np.transpose(arr)
print(arr3)
print(arr3.shape)
print()

arr4 = np.swapaxes(arr1,2,0)
print(arr4)
print(arr4.shape)

(1, 2, 3)

[[[1]
  [5]]

 [[2]
  [6]]

 [[3]
  [7]]]
(3, 2, 1)

[[[1]
  [5]]

 [[2]
  [6]]

 [[3]
  [7]]]
(3, 2, 1)

[[[1]
  [5]]

 [[2]
  [6]]

 [[3]
  [7]]]
(3, 2, 1)


reshape : shape 변경

In [132]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.shape)
print()

arr = arr.reshape(2,2,2)
print(arr)
print(arr.shape)
print()

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)



In [131]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1.shape)
print()

arr2 = arr1.reshape(2,-1,2) # -1 : 남은 차원
print(arr2)
print(arr2.shape)
print()

arr3 = arr1.reshape(-1,2)
print(arr3.shape)
print()

arr4 = arr1.reshape(8) # flatten
print(arr4)
print(arr4.shape)
print()

arr5 = arr1.reshape(-1) # flatten
print(arr5)
print(arr5.shape)

(2, 4)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)

(4, 2)

[1 2 3 4 5 6 7 8]
(8,)

[1 2 3 4 5 6 7 8]
(8,)


- ### Array 4칙 연산

In [181]:
arr1 = np.arange(6).reshape(3,2)
print(arr1)
print()

arr2 = np.arange(7,13).reshape(3,2)
print(arr2)

[[0 1]
 [2 3]
 [4 5]]

[[ 7  8]
 [ 9 10]
 [11 12]]


In [182]:
print(arr1 + arr2) # 더하기
print()
print(arr1 - arr2) # 빼기
print()
print(arr1 * arr2) # 곱하기 (elementwisely)
print()
print(arr1 / arr2) # 나누기 (elementwisely)

[[ 7  9]
 [11 13]
 [15 17]]

[[-7 -7]
 [-7 -7]
 [-7 -7]]

[[ 0  8]
 [18 30]
 [44 60]]

[[0.         0.125     ]
 [0.22222222 0.3       ]
 [0.36363636 0.41666667]]


행렬곱

In [203]:
arr1 = np.arange(6).reshape(3,2)
arr2 = np.arange(7,13).reshape(2,3)
arr3 = np.arange(6)

print(arr1)
print(arr2)
print(arr3)

[[0 1]
 [2 3]
 [4 5]]
[[ 7  8  9]
 [10 11 12]]
[0 1 2 3 4 5]


1. 행렬 내적

In [204]:
arr3.dot(arr3)

55

In [205]:
arr1.dot(arr2)

array([[10, 11, 12],
       [44, 49, 54],
       [78, 87, 96]])

2. 행렬 곱셈

In [206]:
arr3 = np.arange(6)
arr3@arr3

55

In [207]:
arr1@arr2

array([[10, 11, 12],
       [44, 49, 54],
       [78, 87, 96]])

cf. 2차원에서는 둘 다 행렬곱인데, 3차원 이상으로 가면 달라짐

Broadcasting : 알아서 차원을 확장시켜줌?

In [209]:
arr1 = np.arange(6).reshape(3,2)
print(arr1)
print()

arr2 = np.array([1,2])
print(arr2)

[[0 1]
 [2 3]
 [4 5]]

[1 2]


In [210]:
arr1 + arr2

array([[1, 3],
       [3, 5],
       [5, 7]])

In [211]:
arr1 * arr2

array([[ 0,  2],
       [ 2,  6],
       [ 4, 10]])

In [212]:
arr*10

array([[[10, 20],
        [30, 40]],

       [[50, 60],
        [70, 80]]])

In [213]:
arr+2

array([[[ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10]]])

- ### Array 함수

In [215]:
arr = np.arange(8).reshape(2, 4)
print(arr)

[[0 1 2 3]
 [4 5 6 7]]


In [221]:
print(arr.sum())
print(arr.sum(axis=0)) # axis 0을 기준으로 계산
print(arr.sum(axis=1)) # axis 1을 기준으로 계산

28
[ 4  6  8 10]
[ 6 22]


In [228]:
#print(np.sum(arr,axis=0))
print(arr.max())
print(arr.max(axis=0)) # axis 0을 기준으로 계산
print(arr.max(axis=1)) # axis 1을 기준으로 계산

# min도 똑같음

7
[4 5 6 7]
[3 7]


In [223]:
print(arr.argmax())
print(arr.argmax(axis=0)) # axis 0을 기준으로 계산
print(arr.argmax(axis=1)) # axis 1을 기준으로 계산

# argmin도 똑같음

7
[1 1 1 1]
[3 3]


In [235]:
print(np.mean(arr))
print(np.mean(arr,axis=0))
print()

print(np.std(arr))
print(np.var(arr))

3.5
[2. 3. 4. 5.]

2.29128784747792
5.25


In [234]:
print(np.log(arr))
print(np.exp(arr))

[[      -inf 0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947 1.94591015]]
[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]]


C:\Users\ladyc\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


- ### Array 인덱싱

파이썬 기본문법과 거의 유사

In [242]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [241]:
print(arr1[0])
print(arr1[1])
print(arr1[-1])

0
1
9


In [244]:
print(arr1[3:7]) # slicing

[3 4 5 6]


In [246]:
arr2 = np.arange(12).reshape(3,4)
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [258]:
print(arr2[0][1])
print(arr2[2][3])
print(arr2[2][:])
print(arr2[2,:]) # 위랑 같은거
print(arr2[:,3])

1
11
[ 8  9 10 11]
[ 8  9 10 11]
[ 3  7 11]


numpy masking

In [270]:
arr = np.arange(10)*2
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [271]:
arr<5

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [272]:
arr[arr<5]

array([0, 2, 4])

- ### numpy where

In [274]:
np.where(arr<5) # index 보여줌

(array([0, 1, 2], dtype=int64),)

In [277]:
np.where(arr<5,arr*10,0)

array([ 0, 20, 40,  0,  0,  0,  0,  0,  0,  0])

- ### axis 추가/제거

한겹 추가

In [279]:
arr = np.arange(12).reshape(3,4)
arr.shape

(3, 4)

In [289]:
arr[np.newaxis,:,:].shape

(1, 3, 4)

In [285]:
arr.reshape((1,)+arr.shape) 

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [287]:
np.expand_dims(arr,axis=0)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [293]:
arr2 = arr[:,np.newaxis,:]
arr2.shape

(3, 1, 4)

한겹 제거

In [295]:
arr3 = np.squeeze(arr2, axis=1)
arr3.shape

(3, 4)

concatenate

In [300]:
arr1 = np.arange(8).reshape(2,2,2)*10
arr2 = np.arange(8).reshape(2,2,2)*100

arr1, arr2

(array([[[ 0, 10],
         [20, 30]],
 
        [[40, 50],
         [60, 70]]]),
 array([[[  0, 100],
         [200, 300]],
 
        [[400, 500],
         [600, 700]]]))

In [308]:
arr3 = np.concatenate((arr1, arr2),axis=0)
print(arr3)
print(arr3.shape)

[[[  0  10]
  [ 20  30]]

 [[ 40  50]
  [ 60  70]]

 [[  0 100]
  [200 300]]

 [[400 500]
  [600 700]]]
(4, 2, 2)


In [307]:
arr4 = np.concatenate((arr1, arr2),axis=1)
print(arr4)
print(arr4.shape)

[[[  0  10]
  [ 20  30]
  [  0 100]
  [200 300]]

 [[ 40  50]
  [ 60  70]
  [400 500]
  [600 700]]]
(2, 4, 2)


In [309]:
arr4 = np.concatenate((arr1, arr2),axis=2)
print(arr4)
print(arr4.shape)

[[[  0  10   0 100]
  [ 20  30 200 300]]

 [[ 40  50 400 500]
  [ 60  70 600 700]]]
(2, 2, 4)
